version: '3.8'
services:
  config-server:
    image: config-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
  eureka-service:
    image: eureka-service:v1
    ports:
      - "8091:8091"
    restart: always
    depends_on: 
      - config-server    
    networks:
      - springcloud
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    networks:
      - springcloud
    environment: 
      MONGO_INITDB_DATABASE: DbProyect
      MONGO_INITDB_ROOT_USERNAME: admin1
      MONGO_INITDB_ROOT_PASSWORD: admin1
  service-product:
    image: service-product:v1
    ports:
      - "8093:8093"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - mongo:latest
  client-service:
    image: client-service:v1
    ports:
      - "8094:8094"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - mongo:latest
  account-service:
    image: account-service:v1
    ports:
      - "8095:8095"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - mongo:latest
  payments-service:
    image: payments-service:v1
    ports:
      - "8096:8096"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - account-service
      - mongo:latest      
  gateway-service:
    image: gateway-service:v1
    ports:
      - "8092:8092"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - service-product
      - client-service
      - account-service
      - payments-service
networks:
  springcloud: